### ISSUE TITLE
разобраться с makefile для win в gh action

### ISSUE THREAD

**Issue by vtrokhymenko** [quantum-ods/qmlcourse#230]
как видно с отчета https://github.com/SemyonSinchenko/qmlcourse/runs/3990436263?check_suite_focus=true (`test-makefile-os.yml`), то win сборка не собралась. если проблемы со `/`, то нужно обмозговать как сделать так, чтобы это не мешало запускать и на локальных машинах, покуда текущий формат makefile рабочий 

такая же история и с https://github.com/SemyonSinchenko/qmlcourse/runs/3990457619?check_suite_focus=true (`test-psi4-setup.yml`)

**Comment by alexey-pronkin** [comment]
Если честно, не понимаю в чем проблема. Локально у меня работает, можно чуть изменить стиль и все запускать через 
```
python -m pip install
python -m poetry install
python -m poetry run 
```
и т.д. Тогда все точно установится в нужный пайтон и заработает.

**Comment by vtrokhymenko** [comment]
проблема в путях, к примеру этот
```
cmd /C py -V
```
не подходит для github-ного action, а хотело бы, ему нужно больше `/`

**Comment by alexey-pronkin** [comment]
Сейчас ошибка в export токена для dwave, в cmd нужно писать SET вместо EXPORT

**Comment by alexey-pronkin** [comment]
Понятно, корневой каталог на винде выбирается отдельной строкой как :C

**Comment by vtrokhymenko** [comment]
> Сейчас ошибка в export токена для dwave, в cmd нужно писать SET вместо EXPORT

сделайте пж pr сразу, а то с win не дружу, как рак с космосом

**Comment by alexey-pronkin** [comment]
А ты не пробовал сделать 
cmd /C python -V 
? На винде может не корректно прописаны быть алиасы

**Comment by vtrokhymenko** [comment]
> Вроде корректно работает cmd /C, нет? Но зачем это нужно я не очень понимаю, poetry все сам разрулит, если запускать как я выше говорил.

верно, но те workflow для того, чтобы протестировать как работает запуск makefile на всех платформах, и те пути с файла gh action не принимает

> А ты не пробовал сделать
cmd /C python -V

а каком именно месте?

> Завтра починю, я так понял, нужно починить:
билд курса
установку psi4
установку tf.quantum
SET вместо EXPORT
Что ещё?

это горящие, вот созданные задачи для части проблем – #230 #207

**Comment by alexey-pronkin** [comment]
практически разобрался как все работает, возникает мини проблема с тем, что Psi4 можно без боли поставить только в анаконду, они очень много всего используют для сборки от туда, может как-нибудь разделить билд книги и окружение для решения задач, для первого использовать poetry, а для второго - cond'у, но тогда возникнут сложности с примерами в книге, где используется psi4

**Comment by vtrokhymenko** [comment]
не вижу проблем, чтобы книгу на condа завести, главное чтобы все собиралось и примеры были живыми
а tfq нормально поставилась через poetry, без коллизий нужным ему версий библиотек?

**Comment by alexey-pronkin** [comment]
а есть туториал по винде, я не понимаю, почему сейчас не отрабатывает вообще (кучу часов потратил, мб надо на свежую голову подумать) https://github.com/SemyonSinchenko/qmlcourse/blob/fix/fix-windows-problems/.github/workflows/test-makefile-os.yml согласно доке microsoft я вроде все верно сделал cmd /C должно запустить терминал и отработать команду в последующей строке.

**Comment by vtrokhymenko** [comment]
https://semyonsinchenko.github.io/qmlcourse/_build/html/book/pythonblock/python_l2.html#windows

сейчас о win можно уже забыть (будем на docker переделывать), лучше сейчас разобраться с psi4

**Comment by SemyonSinchenko** [comment]
> https://semyonsinchenko.github.io/qmlcourse/_build/html/book/pythonblock/python_l2.html#windows
> 
> сейчас о win можно уже забыть (будем на docker переделывать), лучше сейчас разобраться с psi4

Кмк, вариант с `sys.path.insert(0, "тут конда-окружение с psi4")` должен сработать. Просто в шапку лекции вставить перврй ячейкой.

**Comment by vtrokhymenko** [comment]
и эту conda нужно нам в ci засунуть
