### ISSUE TITLE
исправить названия веток при deploy с pr в aws

### ISSUE THREAD

**Issue by vtrokhymenko** [quantum-ods/qmlcourse#262]
речь идет о cd https://github.com/SemyonSinchenko/qmlcourse/blob/master/.github/workflows/deploy-branch.yml который использует https://github.com/SemyonSinchenko/qmlcourse/blob/master/tools/deploy2aws.py где берется текущая версия ветки, но это не происходит взамен названия pr

в #260 были попытки это решить, но ввиду приоритетов оставили как есть

dod: в http://54.89.156.216 видим нормальные названия веток

**Comment by alexey-pronkin** [comment]
Стоит сделать деплой не автоматически, а по кнопке, иначе 2к минут быстро съедятся

**Comment by vtrokhymenko** [comment]
доп. идея: в скобках (или как-то иначе) возле названия ветки добавлять время когда была собрана книга

**Comment by SemyonSinchenko** [comment]
> доп. идея: в скобках (или как-то иначе) возле названия ветки добавлять время когда была собрана книга

Не, так не выйдет. Сейчас index.hatml, который отдает nginx рендерится джинджой каждый раз заново просто на основе имее тех папок, которые есть на тачке. Деплоить каждый раз в разную папку не вариант, тк место кончится. В теории можно конечно фласк поднять, но тачка не вытянет, там одно ядро вроде и 2 гига оперативы.

**Comment by vtrokhymenko** [comment]
забавно, но когда выполнять `deploy-branch` так сказать руками с помощью `workflow_dispatch `, то имя ветки пишется в нормальном виде
![image](https://user-images.githubusercontent.com/8581044/146758998-b6068a83-7dcf-45ff-af46-da9216e49e62.png)
