### ISSUE TITLE
Рассказать каноничную работу про квантовый отжиг

### ISSUE THREAD

**Issue by SemyonSinchenko** [quantum-ods/qmlcourse#317]
Пересказать основную идею и результаты работы 98-го года про квантовый отжиг.
https://journals.aps.org/pre/pdf/10.1103/PhysRevE.58.5355

В отдельной лекции, которая должна идти как продвинутая в блоке про вариационные алгоритмы.

**Comment by alexey-pronkin** [comment]
Надо расширять prereqs, добавлять туда стох. процессы, чтобы нормально рассказывать про отжиг и для других лекций тоже будет полезно.
