### ISSUE TITLE
Продумать дизайн сборки на двух языках

### ISSUE THREAD

**Issue by SemyonSinchenko** [quantum-ods/qmlcourse#332]
- Продумать как хранить код
- Наверное нужен какой-то модифицированный index.html в качестве главное страницы
- Может быть использовать единые картинки, чтобы еще больше не увеличивать занимаемое место
- Продумать деплой
- Мелочи типа SEO

**Comment by alexey-pronkin** [comment]
Кроме этого, было бы неплохо добавить в название блоков номер недели в начало (с подномером, если два блока и более блока в неделе) , чтобы папки блоков были отсортированы по номеру недели. Иначе каждый раз приходится открывать схему и смотреть что где находится, это отнимает время и не очень интуитивно. Но минусы тогда тоже будут, когда мы захотим поменять очередность, например. Можно что-то другое придумать

**Comment by SemyonSinchenko** [comment]
Если сделать https://github.com/SemyonSinchenko/qmlcourse/discussions/342, то одна лекция может быть одновременно в разных неделях у двух разных треков

**Comment by vtrokhymenko** [comment]
> Кроме этого, было бы неплохо добавить в название блоков номер недели в начало (с подномером, если два блока и более блока в неделе) , чтобы папки блоков были отсортированы по номеру недели. Иначе каждый раз приходится открывать схему и смотреть что где находится, это отнимает время и не очень интуитивно. Но минусы тогда тоже будут, когда мы захотим поменять очередность, например. Можно что-то другое придумать, например в самой лекции хранить ссылку на код этой лекции в мастере.

также думал об этом, но всё может измениться и тогда зря время терять не охота. вон даже сам уже быстро научился искать нужные лекции, а стрельнуть себе в колено всегда успеем

**Comment by vtrokhymenko** [comment]
мы в будущем также планируем иметь 2 языка, а откажется что решали все на буржуйском мать его делать? исходя с этого ответа будет понятно какую именно тропу выбрать
