### ISSUE TITLE
После установки всех необходимых инструментов по инструкции для Ubuntu может потребоваться перезагрузка

### ISSUE THREAD

**Issue by CyberPunk2049** [quantum-ods/qmlcourse#340]
После установки инструментов на Ubuntu при вводе в терминал poetry run jupyter notebook, команда poetry может не находиться. Решение простое, но не такое очевидное - перезагрузиться или перелогиниться. Думаю это стоит добавить в инструкцию.

**Comment by SemyonSinchenko** [comment]
Есть решение проще:
```
source ~/.bashrc
```

Что-то такое лучше добавить.

**Comment by alexey-pronkin** [comment]
Это work-in-progress, я планирую сильно расширить инструкцию. Добавить TL,DR; хранить две версии инструкции с poetry и anaconda, перевести на русский язык. Вот примерно это будет так выглядеть: https://github.com/SemyonSinchenko/qmlcourse/blob/56891f7ccde84081285eeeadc10182dd6fb94d79/INSTALLATION.md
