### ISSUE TITLE
дописать алгоритм Саймона с Qiskit на Pennylane

### ISSUE THREAD

**Issue by Yorko** [quantum-ods/qmlcourse#355]

**Comment by SemyonSinchenko** [comment]
А зачем? Диверсити это хорошо, Qiskit очень популярен и для штук, типа саймона он удобнее кмк

**Comment by vtrokhymenko** [comment]
скорее это вызвано тем, что в начале курса пишем мол дальше только pennylane

**Comment by flatslm** [comment]
Добрый день

Тут имеется в виду реализация qnode c единственным измерением в конце?
Что то навроде:
`NN = 3

dev = qml.device('default.qubit', shots=128, wires=NN*2)

def simon_start(N: int):
  for i in range(N):
          qml.Hadamard(wires=i)

def simon_oracle(N: int):
  qml.CNOT(wires=[0, N])

def simon_after_oracle(N: int):
  for i in range(N):
          qml.Hadamard(wires=i)

@qml.qnode(dev)
def simon_circuit(N: int):
  simon_start(N)
  simon_oracle(N)
  simon_after_oracle(N)
  w = range(0, N*2)
  return qml.probs(wires=w)

fig, ax = qml.draw_mpl(circuit)(N=NN)
fig.show()

simon_result = simon_circuit(N=NN)
print(simon_result)`

Или строгое соответствие описанию алгоритам (т.е. в конце измерение 2-го регистра, а затем снова Hadamar - что в рамках qnode пока не работает, и не понятно - будет ли)?

**Comment by vtrokhymenko** [comment]
@flatslm извините что так долго отвечали^ спасибо за сообщение

суть задачи состоит в том, чтобы код, который сейчас в https://quantum-ods.github.io/qmlcourse/book/qcalgo/simon_algorithm.html#id5 был написан и на pl, соответственно должен делать всё то же самое, что и на qiskit

**Comment by SemyonSinchenko** [comment]
Я может туплю, но в вики схемка с измерениями в конце. https://en.wikipedia.org/wiki/Simon%27s_problem
Оно так получится ведь?

**Comment by flatslm** [comment]
Да, схемка такая получается, но если сравнить с последовательностью шагов 3-4-5 из лекции, (и скорее всего и из оригинальной статьи), то немного расходится. У слушаетелей должны возникнуть вопросы 8 -)
Если ок, то в ближайшие дни вставлю. 
Пулл-реквесты лить на прямую или через свой форк?

**Comment by SemyonSinchenko** [comment]
> Пулл-реквесты лить на прямую или через свой форк?

Через ветку в этом репозитории. Когда PR из форка у нас CI ломался раньше. Ты же в контрибьюторах тут? Или надо добавить?

**Comment by flatslm** [comment]
Да, был в контрибьютерах.

**Comment by flatslm** [comment]
Как бы посмотреть результат мержа?
http://54.89.156.216/370_merge/_build/html/book/ как то не отображает

**Comment by SemyonSinchenko** [comment]
Вот результат:
https://gh-qmlc-deploy-branch.herokuapp.com/book/qcalgo/simon_algorithm.html

Выглядит норм.
