### ISSUE TITLE
Сборка PDF - не хватает стилевых файлов

### ISSUE THREAD

**Issue by Yorko** [quantum-ods/qmlcourse#362]
Действую по инструкции в [Readme](https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2Fquantum-ods%2Fqmlcourse%23build-the-book&cc_key=), ловлю немало ошибок типа "LaTeX Error: File `bbm.sty' not found."

Установил необходимые пакеты, на маке это было `tlmgr install bbm, bbm-macros, pgfplots, fncychap, titlese, tabulary, varwidth, wrapfig, capt-of, needspace`

Далее `xelatex -interaction nonstopmode qmlcourseRU.tex` сабатывает, но ошибки с кириллицей – куча сообщений типа `Missing character: There is no й in font nullfont!`, сходу не поборол. Установил `texlive-lang-cyrillic` – не помогло, как и хождения по Stackoverflow :coolstorybob:

**Comment by vtrokhymenko** [comment]
так в readme написано что «Linux, xelatex». это уже обсуждалось где-то в gh, только вот не помню точно где именно

**Comment by alexey-pronkin** [comment]
Надо каким-нибудь пакетом ставить, где уже всё есть, под macos - хз, не работал на этой системе

**Comment by SemyonSinchenko** [comment]
Это LaTeX, там всегда 100500 ошибок при сборке. Для того и добавлен параметр `-interaction nonstopmode` в команду. @Yorko ты лучше на итоговый файл смотри, он в порядке?

**Comment by Yorko** [comment]
@SemyonSinchenko это я знаю :) но тут реально не сработало, а не просто сообщения. У меня в PDF на выходе вообще кириллических символов нет

**Comment by vtrokhymenko** [comment]
#425 показывает что всё норм
